### ISSUE TITLE
Create many widgets at once

### ISSUE THREAD

**Issue by twopoint718** [begriffs/styleguide_rails#49]
It would be nice to be able to call the generator like this:

```
rails generate styleguide:widget widget_1 widget_2 ... widget_n
```

and generate all those widgets at the same time.

**Comment by begriffs** [comment]
The four-year cleanup -- that's diligence. 😄

**Comment by twopoint718** [comment]
@begriffs the funny thing is, now I depend upon my "issues" tab in the menubar. So I was clearing the decks ;)
